/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskStatus = IDL.Variant({
  'open' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'reward' : IDL.Int,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRegistration = IDL.Record({
  'isApproved' : IDL.Bool,
  'principal' : IDL.Opt(IDL.Principal),
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'passwordHash' : IDL.Text,
});
export const Time = IDL.Int;
export const TaskCompletion = IDL.Record({
  'taskId' : IDL.Nat,
  'timestamp' : Time,
});
export const TasksMetadata = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'isApproved' : IDL.Bool,
  'principal' : IDL.Text,
  'referralCode' : IDL.Text,
  'groupNumber' : IDL.Text,
  'username' : IDL.Text,
  'completedTasks' : IDL.Vec(TaskCompletion),
  'referrals' : IDL.Vec(IDL.Principal),
  'email' : IDL.Text,
  'whatsappNumber' : IDL.Text,
  'passwordHash' : IDL.Text,
  'totalEarnings' : IDL.Int,
});
export const TaskUpdate = IDL.Record({
  'updatedTask' : Task,
  'updatedTitle' : IDL.Text,
  'taskId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTask' : IDL.Func([Task], [], []),
  'addUserRegistration' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Opt(IDL.Principal),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(UserRegistration)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(TasksMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(TasksMetadata)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTasks' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getDailyTasks' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getReferralCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getReferralEarnings' : IDL.Func([], [IDL.Int], ['query']),
  'getRegistration' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserRegistration)],
      ['query'],
    ),
  'getTaskById' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTaskStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTasks' : IDL.Nat,
          'completedTasks' : IDL.Nat,
          'openTasks' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTasksByRewardForCaller' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserPoints' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TasksMetadata)],
      ['query'],
    ),
  'getWeeklyTaskStats' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'completedTasks' : IDL.Nat, 'totalPoints' : IDL.Int })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLoggedIn' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'logout' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([TasksMetadata], [], []),
  'saveCallerUserProfile' : IDL.Func([TasksMetadata], [], []),
  'updateTasks' : IDL.Func([IDL.Vec(TaskUpdate)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskStatus = IDL.Variant({
    'open' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'reward' : IDL.Int,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRegistration = IDL.Record({
    'isApproved' : IDL.Bool,
    'principal' : IDL.Opt(IDL.Principal),
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'passwordHash' : IDL.Text,
  });
  const Time = IDL.Int;
  const TaskCompletion = IDL.Record({ 'taskId' : IDL.Nat, 'timestamp' : Time });
  const TasksMetadata = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'isApproved' : IDL.Bool,
    'principal' : IDL.Text,
    'referralCode' : IDL.Text,
    'groupNumber' : IDL.Text,
    'username' : IDL.Text,
    'completedTasks' : IDL.Vec(TaskCompletion),
    'referrals' : IDL.Vec(IDL.Principal),
    'email' : IDL.Text,
    'whatsappNumber' : IDL.Text,
    'passwordHash' : IDL.Text,
    'totalEarnings' : IDL.Int,
  });
  const TaskUpdate = IDL.Record({
    'updatedTask' : Task,
    'updatedTitle' : IDL.Text,
    'taskId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTask' : IDL.Func([Task], [], []),
    'addUserRegistration' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Opt(IDL.Principal),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllRegistrations' : IDL.Func(
        [],
        [IDL.Vec(UserRegistration)],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(TasksMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(TasksMetadata)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTasks' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getDailyTasks' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
    'getReferralCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getReferralEarnings' : IDL.Func([], [IDL.Int], ['query']),
    'getRegistration' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserRegistration)],
        ['query'],
      ),
    'getTaskById' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTaskStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTasks' : IDL.Nat,
            'completedTasks' : IDL.Nat,
            'openTasks' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTasksByRewardForCaller' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserPoints' : IDL.Func([IDL.Principal], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TasksMetadata)],
        ['query'],
      ),
    'getWeeklyTaskStats' : IDL.Func(
        [IDL.Principal],
        [IDL.Record({ 'completedTasks' : IDL.Nat, 'totalPoints' : IDL.Int })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLoggedIn' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'logout' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([TasksMetadata], [], []),
    'saveCallerUserProfile' : IDL.Func([TasksMetadata], [], []),
    'updateTasks' : IDL.Func([IDL.Vec(TaskUpdate)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };