/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'reward' : bigint,
  'title' : string,
  'description' : string,
}
export interface TaskCompletion { 'taskId' : bigint, 'timestamp' : Time }
export type TaskStatus = { 'open' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export interface TaskUpdate {
  'updatedTask' : Task,
  'updatedTitle' : string,
  'taskId' : bigint,
}
export interface TasksMetadata {
  'tasks' : Array<Task>,
  'isApproved' : boolean,
  'principal' : string,
  'referralCode' : string,
  'groupNumber' : string,
  'username' : string,
  'completedTasks' : Array<TaskCompletion>,
  'referrals' : Array<Principal>,
  'email' : string,
  'whatsappNumber' : string,
  'passwordHash' : string,
  'totalEarnings' : bigint,
}
export type Time = bigint;
export interface UserRegistration {
  'isApproved' : boolean,
  'principal' : [] | [Principal],
  'referralCode' : string,
  'username' : string,
  'email' : string,
  'whatsappNumber' : string,
  'passwordHash' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTask' : ActorMethod<[Task], undefined>,
  'addUserRegistration' : ActorMethod<
    [string, string, string, string, string, string, boolean, [] | [Principal]],
    undefined
  >,
  'approveUser' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllRegistrations' : ActorMethod<[], Array<UserRegistration>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUsers' : ActorMethod<[], Array<TasksMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [TasksMetadata]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTasks' : ActorMethod<[Principal], Array<bigint>>,
  'getDailyTasks' : ActorMethod<[Principal], Array<Task>>,
  'getReferralCount' : ActorMethod<[], bigint>,
  'getReferralEarnings' : ActorMethod<[], bigint>,
  'getRegistration' : ActorMethod<[string], [] | [UserRegistration]>,
  'getTaskById' : ActorMethod<[bigint], [] | [Task]>,
  'getTaskStats' : ActorMethod<
    [],
    { 'totalTasks' : bigint, 'completedTasks' : bigint, 'openTasks' : bigint }
  >,
  'getTasksByRewardForCaller' : ActorMethod<[], Array<Task>>,
  'getUserPoints' : ActorMethod<[Principal], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [TasksMetadata]>,
  'getWeeklyTaskStats' : ActorMethod<
    [Principal],
    { 'completedTasks' : bigint, 'totalPoints' : bigint }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLoggedIn' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], boolean>,
  'logout' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[TasksMetadata], undefined>,
  'saveCallerUserProfile' : ActorMethod<[TasksMetadata], undefined>,
  'updateTasks' : ActorMethod<[Array<TaskUpdate>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];