/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaskUpdate {
    updatedTask: Task;
    updatedTitle: string;
    taskId: bigint;
}
export type Time = bigint;
export interface TaskCompletion {
    taskId: bigint;
    timestamp: Time;
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    reward: bigint;
    title: string;
    description: string;
}
export interface UserProfile {
    tasks: Array<Task>;
    isApproved: boolean;
    referralCode: string;
    groupNumber: string;
    username: string;
    completedTasks: Array<TaskCompletion>;
    referrals: Array<Principal>;
    email: string;
    whatsappNumber: string;
    passwordHash: string;
    totalEarnings: bigint;
}
export enum TaskStatus {
    open = "open",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTask(task: Task): Promise<void>;
    approveUser(user: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeTask(taskId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    exists(tasks: Array<TaskCompletion>, taskId: bigint): Promise<boolean>;
    getAllTasks(): Promise<Array<Task>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompletedTasks(user: Principal): Promise<Array<bigint>>;
    getDailyTasks(user: Principal): Promise<Array<Task>>;
    getReferralCount(): Promise<bigint>;
    getReferralEarnings(): Promise<bigint>;
    getTaskById(taskId: bigint): Promise<Task | null>;
    getTaskStats(): Promise<{
        totalTasks: bigint;
        completedTasks: bigint;
        openTasks: bigint;
    }>;
    getTasksByRewardForCaller(): Promise<Array<Task>>;
    getUserPoints(user: Principal): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeeklyTaskStats(user: Principal): Promise<{
        completedTasks: bigint;
        totalPoints: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isLoggedIn(): Promise<boolean>;
    legacyAdminLogin(username: string, password: string): Promise<boolean>;
    login(username: string, password: string): Promise<boolean>;
    logout(): Promise<void>;
    registerUser(profile: UserProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTasks(taskUpdates: Array<TaskUpdate>): Promise<void>;
}
import type { Task as _Task, TaskCompletion as _TaskCompletion, TaskStatus as _TaskStatus, TaskUpdate as _TaskUpdate, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(to_candid_Task_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(to_candid_Task_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveUser(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTask(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async exists(arg0: Array<TaskCompletion>, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.exists(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exists(arg0, arg1);
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedTasks(arg0: Principal): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedTasks(arg0);
            return result;
        }
    }
    async getDailyTasks(arg0: Principal): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTasks(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTasks(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCount();
            return result;
        }
    }
    async getReferralEarnings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralEarnings();
            return result;
        }
    }
    async getTaskById(arg0: bigint): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskStats(): Promise<{
        totalTasks: bigint;
        completedTasks: bigint;
        openTasks: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskStats();
            return result;
        }
    }
    async getTasksByRewardForCaller(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByRewardForCaller();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByRewardForCaller();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPoints(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPoints(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyTaskStats(arg0: Principal): Promise<{
        completedTasks: bigint;
        totalPoints: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyTaskStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyTaskStats(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isLoggedIn(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLoggedIn();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLoggedIn();
            return result;
        }
    }
    async legacyAdminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.legacyAdminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.legacyAdminLogin(arg0, arg1);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async logout(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout();
            return result;
        }
    }
    async registerUser(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTasks(arg0: Array<TaskUpdate>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTasks(to_candid_vec_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTasks(to_candid_vec_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_TaskStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_Task>;
    isApproved: boolean;
    referralCode: string;
    groupNumber: string;
    username: string;
    completedTasks: Array<_TaskCompletion>;
    referrals: Array<Principal>;
    email: string;
    whatsappNumber: string;
    passwordHash: string;
    totalEarnings: bigint;
}): {
    tasks: Array<Task>;
    isApproved: boolean;
    referralCode: string;
    groupNumber: string;
    username: string;
    completedTasks: Array<TaskCompletion>;
    referrals: Array<Principal>;
    email: string;
    whatsappNumber: string;
    passwordHash: string;
    totalEarnings: bigint;
} {
    return {
        tasks: from_candid_vec_n7(_uploadFile, _downloadFile, value.tasks),
        isApproved: value.isApproved,
        referralCode: value.referralCode,
        groupNumber: value.groupNumber,
        username: value.username,
        completedTasks: value.completedTasks,
        referrals: value.referrals,
        email: value.email,
        whatsappNumber: value.whatsappNumber,
        passwordHash: value.passwordHash,
        totalEarnings: value.totalEarnings
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    reward: bigint;
    title: string;
    description: string;
}): {
    id: bigint;
    status: TaskStatus;
    reward: bigint;
    title: string;
    description: string;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n10(_uploadFile, _downloadFile, value.status),
        reward: value.reward,
        title: value.title,
        description: value.description
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "open" in value ? TaskStatus.open : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n8(_uploadFile, _downloadFile, x));
}
function to_candid_TaskStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskUpdate_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskUpdate): _TaskUpdate {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: TaskStatus;
    reward: bigint;
    title: string;
    description: string;
}): {
    id: bigint;
    status: _TaskStatus;
    reward: bigint;
    title: string;
    description: string;
} {
    return {
        id: value.id,
        status: to_candid_TaskStatus_n3(_uploadFile, _downloadFile, value.status),
        reward: value.reward,
        title: value.title,
        description: value.description
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<Task>;
    isApproved: boolean;
    referralCode: string;
    groupNumber: string;
    username: string;
    completedTasks: Array<TaskCompletion>;
    referrals: Array<Principal>;
    email: string;
    whatsappNumber: string;
    passwordHash: string;
    totalEarnings: bigint;
}): {
    tasks: Array<_Task>;
    isApproved: boolean;
    referralCode: string;
    groupNumber: string;
    username: string;
    completedTasks: Array<_TaskCompletion>;
    referrals: Array<Principal>;
    email: string;
    whatsappNumber: string;
    passwordHash: string;
    totalEarnings: bigint;
} {
    return {
        tasks: to_candid_vec_n21(_uploadFile, _downloadFile, value.tasks),
        isApproved: value.isApproved,
        referralCode: value.referralCode,
        groupNumber: value.groupNumber,
        username: value.username,
        completedTasks: value.completedTasks,
        referrals: value.referrals,
        email: value.email,
        whatsappNumber: value.whatsappNumber,
        passwordHash: value.passwordHash,
        totalEarnings: value.totalEarnings
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    updatedTask: Task;
    updatedTitle: string;
    taskId: bigint;
}): {
    updatedTask: _Task;
    updatedTitle: string;
    taskId: bigint;
} {
    return {
        updatedTask: to_candid_Task_n1(_uploadFile, _downloadFile, value.updatedTask),
        updatedTitle: value.updatedTitle,
        taskId: value.taskId
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    open: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.open ? {
        open: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Task>): Array<_Task> {
    return value.map((x)=>to_candid_Task_n1(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TaskUpdate>): Array<_TaskUpdate> {
    return value.map((x)=>to_candid_TaskUpdate_n23(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
